-- Importação de seed/japanese_curriculum_seed.json (55 exercícios no arquivo,
-- categorias saudacoes_apresentacao até conversa_social, sprint_day_ref 1-50).
-- Dedupe feito por expected_transcript exato contra o que já existia (migration
-- 0004): 1 colisão encontrada ('こんにちは', já seedado na Fase 3) — pulada,
-- não repetida aqui. Os 54 restantes são novos.
-- Formato pedagógico interno (Sec. 10 CLAUDE.md): zero kanji, zero gramática
-- literária — só o essencial pra sobrevivência conversacional.

INSERT INTO exercises (category, difficulty, prompt_pt, expected_transcript, expected_romaji, sprint_day_ref, language) VALUES
('saudacoes_apresentacao', 1, 'Cumprimente formalmente dizendo bom dia.', 'おはようございます', 'ohayou gozaimasu', 1, 'ja-JP'),
('saudacoes_apresentacao', 2, 'Se apresente formalmente dizendo seu nome, num contexto de trabalho.', 'はじめまして、モイゼスともうします', 'hajimemashite, Moisés to moushimasu', 2, 'ja-JP'),
('saudacoes_apresentacao', 2, 'Peça pra a pessoa cuidar bem de você (fórmula de fechamento de apresentação).', 'どうぞよろしくおねがいします', 'douzo yoroshiku onegaishimasu', 3, 'ja-JP'),
('compras_konbini', 1, 'Diga que não precisa do saco plástico.', 'ふくろはいりません', 'fukuro wa irimasen', 6, 'ja-JP'),
('compras_konbini', 1, 'Peça um item apontando: ''isso, por favor''.', 'これをください', 'kore wo kudasai', 6, 'ja-JP'),
('compras_konbini', 2, 'Pergunte se aceitam cartão de crédito.', 'クレジットカードはつかえますか', 'kurejitto kaado wa tsukaemasu ka', 7, 'ja-JP'),
('compras_konbini', 2, 'Peça o recibo.', 'レシートをください', 'reshiito wo kudasai', 8, 'ja-JP'),
('compras_konbini', 3, 'Pergunte se tem algo um pouco mais barato.', 'もうすこしやすいのはありますか', 'mou sukoshi yasui no wa arimasu ka', 9, 'ja-JP'),
('compras_konbini', 2, 'Pergunte onde fica um item na loja.', 'どこにありますか', 'doko ni arimasu ka', 10, 'ja-JP'),
('restaurante', 1, 'Peça pra ver o cardápio.', 'メニューをみせてください', 'menyuu wo misete kudasai', 11, 'ja-JP'),
('restaurante', 2, 'Pergunte o que o garçom recomenda.', 'おすすめはなんですか', 'osusume wa nan desu ka', 12, 'ja-JP'),
('restaurante', 1, 'Faça o pedido apontando pro item: ''isso, por favor''.', 'これをおねがいします', 'kore wo onegaishimasu', 12, 'ja-JP'),
('restaurante', 2, 'Peça a conta.', 'おかいけいおねがいします', 'okaikei onegaishimasu', 13, 'ja-JP'),
('restaurante', 1, 'Peça um copo d''água.', 'おみずをください', 'omizu wo kudasai', 14, 'ja-JP'),
('restaurante', 2, 'Diga que estava muito gostoso, ao terminar a refeição.', 'とてもおいしかったです', 'totemo oishikatta desu', 15, 'ja-JP'),
('direcoes_transporte', 2, 'Pergunte onde fica a estação.', 'えきはどこですか', 'eki wa doko desu ka', 16, 'ja-JP'),
('direcoes_transporte', 1, 'Pergunte se é perto daqui.', 'ちかいですか', 'chikai desu ka', 16, 'ja-JP'),
('direcoes_transporte', 3, 'Pergunte quanto tempo demora a pé.', 'あるいてどのくらいですか', 'aruite dono kurai desu ka', 17, 'ja-JP'),
('direcoes_transporte', 2, 'Peça pra chamarem um táxi.', 'タクシーをよんでください', 'takushii wo yonde kudasai', 18, 'ja-JP'),
('direcoes_transporte', 3, 'Pergunte se esse trem vai pra Tóquio.', 'このでんしゃはとうきょうにいきますか', 'kono densha wa toukyou ni ikimasu ka', 19, 'ja-JP'),
('direcoes_transporte', 2, 'Diga que está perdido.', 'みちにまよいました', 'michi ni mayoimashita', 20, 'ja-JP'),
('emergencia_saude', 2, 'Peça ajuda numa emergência.', 'たすけてください', 'tasukete kudasai', 21, 'ja-JP'),
('emergencia_saude', 2, 'Pergunte onde fica o hospital.', 'びょういんはどこですか', 'byouin wa doko desu ka', 22, 'ja-JP'),
('emergencia_saude', 2, 'Diga que não está se sentindo bem.', 'きぶんがわるいです', 'kibun ga warui desu', 22, 'ja-JP'),
('emergencia_saude', 3, 'Peça pra chamarem a polícia.', 'けいさつをよんでください', 'keisatsu wo yonde kudasai', 23, 'ja-JP'),
('emergencia_saude', 3, 'Diga que perdeu o passaporte.', 'パスポートをなくしました', 'pasupooto wo nakushimashita', 24, 'ja-JP'),
('emergencia_saude', 2, 'Pergunte se tem algum remédio disponível.', 'くすりはありますか', 'kusuri wa arimasu ka', 25, 'ja-JP'),
('trabalho_escritorio', 2, 'Peça desculpas pelo atraso.', 'おそくなってすみません', 'osoku natte sumimasen', 26, 'ja-JP'),
('trabalho_escritorio', 2, 'Peça pra repetirem mais uma vez.', 'もういちどおねがいします', 'mou ichido onegaishimasu', 27, 'ja-JP'),
('trabalho_escritorio', 3, 'Pergunte a que horas começa a reunião.', 'かいぎはなんじからですか', 'kaigi wa nanji kara desu ka', 28, 'ja-JP'),
('trabalho_escritorio', 2, 'Peça pra pessoa aguardar um momento.', 'しょうしょうおまちください', 'shoushou omachi kudasai', 29, 'ja-JP'),
('trabalho_escritorio', 3, 'Diga que vai tirar folga hoje.', 'きょうはやすみをとります', 'kyou wa yasumi wo torimasu', 30, 'ja-JP'),
('numeros_horarios', 1, 'Pergunte que horas são agora.', 'いまなんじですか', 'ima nanji desu ka', 31, 'ja-JP'),
('numeros_horarios', 3, 'Combine de se encontrar às 9 da manhã.', 'ごぜんくじにあいましょう', 'gozen kuji ni aimashou', 32, 'ja-JP'),
('numeros_horarios', 1, 'Peça uma unidade de um item.', 'ひとつください', 'hitotsu kudasai', 33, 'ja-JP'),
('numeros_horarios', 2, 'Pergunte quanto é no total.', 'ぜんぶでいくらですか', 'zenbu de ikura desu ka', 34, 'ja-JP'),
('numeros_horarios', 3, 'Pergunte que dia da semana é amanhã.', 'あしたはなんようびですか', 'ashita wa nan youbi desu ka', 35, 'ja-JP'),
('telefone_agendamento', 1, 'Atenda o telefone.', 'もしもし', 'moshi moshi', 36, 'ja-JP'),
('telefone_agendamento', 3, 'Peça o número de telefone da pessoa.', 'でんわばんごうをおしえてください', 'denwa bangou wo oshiete kudasai', 37, 'ja-JP'),
('telefone_agendamento', 2, 'Diga que vai ligar de volta depois.', 'あとでかけなおします', 'ato de kakenaoshimasu', 37, 'ja-JP'),
('telefone_agendamento', 2, 'Diga que quer fazer uma reserva.', 'よやくをしたいです', 'yoyaku wo shitai desu', 38, 'ja-JP'),
('telefone_agendamento', 2, 'Peça pra cancelar algo.', 'キャンセルしてください', 'kyanseru shite kudasai', 39, 'ja-JP'),
('telefone_agendamento', 3, 'Pergunte se dá pra mudar o horário combinado.', 'スケジュールをへんこうできますか', 'sukejuuru wo henkou dekimasu ka', 40, 'ja-JP'),
('moradia_cotidiano', 2, 'Diga que a luz não acende.', 'でんきがつきません', 'denki ga tsukimasen', 41, 'ja-JP'),
('moradia_cotidiano', 3, 'Diga que a internet não conecta.', 'インターネットがつながりません', 'intaanetto ga tsunagarimasen', 42, 'ja-JP'),
('moradia_cotidiano', 2, 'Pergunte quanto é o aluguel.', 'やちんはいくらですか', 'yachin wa ikura desu ka', 43, 'ja-JP'),
('moradia_cotidiano', 2, 'Pergunte onde joga o lixo.', 'ゴミはどこにすてますか', 'gomi wa doko ni sutemasu ka', 44, 'ja-JP'),
('moradia_cotidiano', 3, 'Diga que quer usar a máquina de lavar.', 'せんたくきをつかいたいです', 'sentakuki wo tsukaitai desu', 45, 'ja-JP'),
('conversa_social', 2, 'Pergunte qual é o hobby da pessoa.', 'しゅみはなんですか', 'shumi wa nan desu ka', 46, 'ja-JP'),
('conversa_social', 2, 'Pergunte se a pessoa gosta do Japão.', 'にほんはすきですか', 'nihon wa suki desu ka', 47, 'ja-JP'),
('conversa_social', 1, 'Comente casualmente que hoje está quente.', 'きょうはあついですね', 'kyou wa atsui desu ne', 48, 'ja-JP'),
('conversa_social', 2, 'Pergunte o que a pessoa faz no fim de semana.', 'しゅうまつはなにをしますか', 'shuumatsu wa nani wo shimasu ka', 49, 'ja-JP'),
('conversa_social', 2, 'Se despeça combinando de se ver de novo amanhã.', 'またあしたあいましょう', 'mata ashita aimashou', 50, 'ja-JP'),
('conversa_social', 1, 'Se despeça desejando que a pessoa se cuide.', 'おげんきで', 'o genki de', 50, 'ja-JP');
