DELETE FROM exercises WHERE language = 'en-US' AND expected_transcript IN (
    'hi, how are you?',
    'I''m good, thanks. And you?',
    'my name is Moisés',
    'nice to meet you',
    'I have to go, it was good seeing you',
    'how much does this cost?',
    'I''m just looking, thanks',
    'do you accept credit cards?',
    'I''d like to exchange this, it''s defective',
    'where is the fitting room?',
    'a table for two, please',
    'what do you recommend?',
    'can I have the check, please?',
    'I''m allergic to peanuts',
    'a glass of still water, please',
    'how do I get to the nearest subway station?',
    'is it close to here?',
    'I''m lost, can you help me?',
    'can you call me a taxi?',
    'how long does it take on foot?',
    'I need a doctor',
    'I''m not feeling well',
    'I lost my passport',
    'please call the police',
    'where is the nearest hospital?',
    'I work as a software developer',
    'sorry I''m late',
    'can we reschedule the meeting?',
    'sorry, could you repeat that?',
    'I''ll think about the offer and get back to you soon'
);
